name: Push json to airtable

on:
  schedule:
  # Run at every hour of the day
    - cron: "0 */1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_commit:
    name: Scrape and Commit to Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.24.0
        with:
          elixir-version: "1.19.5"
          otp-version: "28.0"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        id: build-cache
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}-
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: mix deps.get

      - name: Push to Airtable
        run: mix compile --force && mix create.airtable
        env:
          TOKEN: ${{ secrets.TOKEN }}
